services:
  - type: web
    name: proyectocementerio
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn cementerio_config.wsgi:application
